(function(){function n(a,c,f,d){this.name=function(){return a};this.abbrev=function(){return c};this.symbol=function(){return f};this.color=function(){return d}}function b(a,c,f){this.name=function(){return a};this.abbrev=function(){return c};this.value=function(){return f}}function o(a,c){this.rank=function(){return a};this.suit=function(){return c}}function y(a){function c(){for(var g=a.length-1;g>=0;--g)d.push(a[g])}function f(){var g=n.values,h=b.values,q,l;for(q=0;q<g.length;++q)for(l=0;l<h.length;++l)d.push(new o(h[l],
g[q]))}var d=[];a?c():f();this.cardCount=function(){return d.length};this.cardAtIndex=function(g){return d[g]};this.cardWithName=function(g){return B(d,function(h){return h.name()===g})};this.swapCardsAtIndices=function(g,h){var q=d[g];d[g]=d[h];d[h]=q};this.drawCard=function(){if(d.length<1)throw new Error("Deck is empty");return d.pop()};this.toData=function(){var g,h=[];for(g=0;g<d.length;++g)h.push(d[g].toData());return h}}function z(a,c){var f,d;if(c)f=c;else{f=[];for(d=0;d<5;++d)f.push(a.drawCard())}this.toString=
function(){return"Hand: "+f.toString()};this.cardCount=function(){return f.length};this.cardAtIndex=function(g){return f[g]};this.discardAtIndex=function(g){f[g]=null};this.draw=function(){for(d=0;d<5;++d)if(f[d]==null)f[d]=a.drawCard()};this.toData=function(){var g,h=[];for(g=0;g<f.length;++g)h.push(f[g].toData());return{cards:h,deck:a.toData()}}}function e(a,c){this.name=function(){return a};this.payoutForWager=function(f){return c[f]}}function m(a){this.toString=this.name=function(){return a};
this.toData=function(){return a}}function D(a){var c,f,d,g,h,q;c=a&&a.playState?m.fromData(a.playState):m.gameIdle;d=a&&typeof a.credits!=="undefined"?a.credits:100;g=a&&a.wager?a.wager:5;if(a&&a.hand)f=z.fromData(a.hand);if(a&&a.lastHandScore)h=e.fromData(a.lastHandScore);if(a)q=a.lastHandPayout;this.onGameEnded=this.onDrawComplete=this.onDealComplate=null;this.playState=function(){return c};this.credits=function(){return d};this.wager=function(){return g};this.addCredits=function(l){d+=l};this.shuffleAndDeal=
function(){var l=new y;l.shuffle();this.dealWithDeck(l)};this.dealWithDeck=function(l){d-=g;f=new z(l);c=m.gameStarted;this.onDealComplete&&this.onDealComplete()};this.cardAtIndex=function(l){return f.cardAtIndex(l)};this.discardAtIndex=function(l){if(c!==m.gameStarted)throw new Error("cannot discard unless playState is gameStarted");f.discardAtIndex(l)};this.draw=function(){if(c!==m.gameStarted)throw new Error("cannot draw unless playState is gameStarted");f.draw();c=m.afterDraw;this.onDrawComplete&&
this.onDrawComplete()};this.scoreHand=function(){if(c!==m.afterDraw)throw new Error("cannot score hand until after draw");h=f.score();q=h.payoutForWager(g);d+=q;c=m.gameEnded;this.onGameEnded&&this.onGameEnded()};this.lastHandScore=function(){return h};this.lastHandPayout=function(){return q};this.toData=function(){return{playState:c.toData(),credits:d,wager:g,hand:f?f.toData():null,lastHandScore:h?h.toData():null,lastHandPayout:q}};this.storeTo=function(l,s){var E=this.toData();E=JSON.stringify(E);
l.setItem(s,E)}}var v=kjUtil.newObjectWithPrototype,B=kjUtil.findElement;n.clubs=new n("clubs","c","\u2663","#000000");n.hearts=new n("hearts","h","\u2665","#FF0000");n.diamonds=new n("diamonds","d","\u2666","#FF0000");n.spades=new n("spades","s","\u2660","#000000");n.values=[n.clubs,n.diamonds,n.hearts,n.spades];n.prototype.toString=function(){return this.name()};n.withName=function(a){return B(n.values,function(c){return c.name()===a})};n.withAbbrev=function(a){return B(n.values,function(c){return c.abbrev()===
a})};b.two=new b("two","2",2);b.three=new b("three","3",3);b.four=new b("four","4",4);b.five=new b("five","5",5);b.six=new b("six","6",6);b.seven=new b("seven","7",7);b.eight=new b("eight","8",8);b.nine=new b("nine","9",9);b.ten=new b("ten","t",10);b.jack=new b("jack","j",11);b.queen=new b("queen","q",12);b.king=new b("king","k",13);b.ace=new b("ace","a",14);b.values=[b.ace,b.king,b.queen,b.jack,b.ten,b.nine,b.eight,b.seven,b.six,b.five,b.four,b.three,b.two];b.withName=function(a){return B(b.values,
function(c){return c.name()===a})};b.withValue=function(a){return B(b.values,function(c){return c.value()===a})};b.prototype.toString=function(){return this.name()};o.withNameAndSuit=function(a,c){return new o(b.withName(a),c)};o.arrayFromNamesAndSuits=function(a){var c=[],f=a.length/2,d,g,h;for(h=0;h<f;++h){d=a[h*2];g=a[h*2+1];c.push(o.withNameAndSuit(d,g))}return c};o.prototype.rankName=function(){return this.rank().name()};o.prototype.rankAbbrev=function(){return this.rank().abbrev()};o.prototype.rankValue=
function(){return this.rank().value()};o.prototype.suitName=function(){return this.suit().name()};o.prototype.suitColor=function(){return this.suit().color()};o.prototype.suitAbbrev=function(){return this.suit().abbrev()};o.prototype.suitSymbol=function(){return this.suit().symbol()};o.prototype.name=function(){return this.rankName()+" of "+this.suitName()};o.prototype.toString=function(){return this.name()};o.prototype.abbrev=function(){return this.rankAbbrev()+this.suitAbbrev()};o.prototype.html=
function(){return'<span style="color:'+this.suitColor()+';">'+this.abbrev()+"</span>"};o.prototype.toData=function(){return[this.rankValue(),this.suitAbbrev()]};o.fromData=function(a){var c=b.withValue(a[0]);suitAbbrev=a[1];suit=n.withAbbrev(suitAbbrev);return new o(c,suit)};y.fromData=function(a){var c,f=[];for(c=0;c<a.length;++c)f.push(o.fromData(a[c]));return new y(f)};y.fromNamesAndSuits=function(a){a=o.arrayFromNamesAndSuits(a);return new y(a)};y.prototype.shuffle=function(){function a(d){return Math.floor(Math.random()*
d)}var c,f;for(c=this.cardCount()-1;c>0;--c){f=a(c+1);f!==c&&this.swapCardsAtIndices(c,f)}};z.fromData=function(a){var c=a.cards,f=[];a=y.fromData(a.deck);var d,g;for(d=0;d<c.length;++d){g=o.fromData(c[d]);f.push(g)}return new z(a,f)};z.fromDeckWithNamesAndSuits=function(a){a=y.fromNamesAndSuits(a);return new z(a)};z.prototype.score=function(){return e.forHand(this)};e.loss=new e("Loss",{1:0,2:0,3:0,4:0,5:0});e.onePair=new e("One Pair",{1:1,2:2,3:3,4:4,5:5});e.twoPair=new e("Two Pair",{1:2,2:4,3:6,
4:8,5:10});e.threeOfAKind=new e("Three of a Kind",{1:3,2:6,3:9,4:12,5:15});e.straight=new e("Straight",{1:4,2:8,3:12,4:16,5:20});e.flush=new e("Flush",{1:6,2:12,3:18,4:24,5:30});e.fullHouse=new e("Full House",{1:9,2:18,3:27,4:36,5:45});e.fourOfAKind=new e("Four of a Kind",{1:25,2:50,3:75,4:100,5:125});e.straightFlush=new e("Straight Flush",{1:50,2:100,3:150,4:200,5:250});e.royalFlush=new e("Royal Flush",{1:250,2:500,3:750,4:1E3,5:4E3});e.values=[e.loss,e.onePair,e.twoPair,e.threeOfAKind,e.straight,
e.flush,e.fourOfAKind,e.straightFlush,e.royalFlush];e.withName=function(a){return B(e.values,function(c){return c.name()===a})};e.forHand=function(a){function c(){var i=b.values,j;w={};for(j=0;j<i.length;++j)w[i[j].name()]=0}function f(i){i=i.name();w[i]+=1}function d(i){var j=b.values,k,p;for(p=0;p<j.length;++p){k=j[p];if(w[k.name()]===i){C=k;return true}}return false}function g(){var i=n.values,j;G={};for(j=0;j<i.length;++j)G[i[j].name()]=0}function h(i){i=i.name();G[i]+=1}function q(){var i=a.cardCount(),
j,k;c();g();for(k=0;k<i;++k){j=a.cardAtIndex(k);f(j.rank());h(j.suit())}}function l(){return[0,1,2,3,4]}function s(i){var j=a.cardCount(),k=[],p,u;for(p=0;p<j;++p){u=a.cardAtIndex(p);u.rank()===i&&k.push(p)}return k}function E(i,j){var k=a.cardCount(),p=[],u,F;for(u=0;u<k;++u){F=a.cardAtIndex(u);F=F.rank();if(F===i||F===j)p.push(u)}return p}function K(){if(d(4)){t=C;x=s(t);return true}return false}function L(){if(d(3)){t=C;x=s(t);return true}return false}function M(){var i=b.values,j,k,p;for(k=0;k<
i.length;++k){p=i[k];if(w[p.name()]===2)if(j){t=j;A=p;x=E(t,A);return true}else j=p}return false}function N(){if(d(2)&&C.value()>=b.jack.value()){t=C;x=s(t);return true}return false}function O(){var i;if(d(3)){i=C;if(d(2)){t=i;A=C;x=l();return true}}return false}function P(){function i(){return w[b.ace.name()]>0&&w[b.two.name()]>0&&w[b.three.name()]>0&&w[b.four.name()]>0&&w[b.five.name()]>0}function j(p){for(var u=0;u<5;++u)if(w[b.values[p+u].name()]===0)return false;return true}for(var k=0;k<9;++k)if(j(k)){t=
b.values[k];A=b.values[k+4];x=l();return true}if(i()){t=b.five;A=b.ace;x=l();return true}return false}function Q(){var i=n.values,j,k;for(j=0;j<i.length;++j){k=i[j];if(G[k.name()]===5){H=k;x=l();return true}}return false}var w,G,C,t,A,H,x,I,J,r;q();I=P();J=Q();if(I&&J)r=t===b.ace?v(e.royalFlush):v(e.straightFlush);else if(K())r=v(e.fourOfAKind);else if(O())r=v(e.fullHouse);else if(J)r=v(e.flush);else if(I)r=v(e.straight);else if(L())r=v(e.threeOfAKind);else if(M())r=v(e.twoPair);else if(N())r=v(e.onePair);
else{r=v(e.loss);x=[]}r.majorRank=function(){return t};r.rank=r.majorRank;r.minorRank=function(){return A};r.suit=function(){return H};r.scoringCardIndexes=function(){return x};r.toData=function(){return{name:r.name(),majorRank:t?t.name():null,minorRank:A?A.name():null,suit:H?H.name():null,scoringCardIndexes:x}};return r};e.fromData=function(a){var c=a.majorRank,f=a.minorRank,d=a.suit,g=a.scoringCardIndexes;a=e.withName(a.name);var h=c?b.withName(c):null,q=f?b.withName(f):null,l=d?n.withName(d):null,
s=v(a);s.majorRank=function(){return h};s.rank=s.majorRank;s.minorRank=function(){return q};s.suit=function(){return l};s.scoringCardIndexes=function(){return g};s.toData=function(){return{name:s.name(),majorRank:h?h.name():null,minorRank:q?q.name():null,suit:l?l.name():null,scoringCardIndexes:g}};return s};m.gameIdle=new m("game idle");m.gameStarted=new m("game started");m.afterDraw=new m("after draw");m.gameEnded=new m("game ended");m.values=[m.gameIdle,m.gameStarted,m.afterDraw,m.gameEnded];m.withName=
function(a){return B(m.values,function(c){return c.name()===a})};m.fromData=function(a){return m.withName(a)};D.fromData=function(a){return new D(a)};D.restoreFrom=function(a,c){a=a.getItem(c);if(!a)return null;a=JSON.parse(a);return D.fromData(a)};this.kjPoker={colorRed:"#FF0000",colorBlack:"#000000",Card:o,Suit:n,Rank:b,Deck:y,Hand:z,Score:e,PlayState:m,Session:D}})();
